#!/bin/sh

echo "pre-commit started"
files=$(git diff --cached --name-only --diff-filter=ACM)

jsfiles=$(  grep ".js$" <<< "$files")
javafiles=$(  grep ".java$" <<< "$files")
#jsfiles=[[ $files == *.js* ]]
#javafiles=[[ $files === *.java* ]]


if [ "$files" = "" ]; then 
    exit 0 
fi

pass=true

#echo "\t\e[34mValidating JavaScript:\t\e[0m"
echo "\n\033[46mValidating JavaScript:\033[0m\n"

for jsfile in ${jsfiles}; do
    lintErrors=$(jshint ${jsfile} )
    #result=$lintErrors | $( grep "${file} is OK")
    
    if [ ${#lintErrors} -eq 0 ]
    then
        echo "\033[32mJSHint Passed: ${jsfile}\033[0m"
    else
        echo "\033[31mJSHint Failed: ${jsfile}\033[0m"
        echo "$lintErrors"
        pass=false
    fi
done

echo "\n\033[46mJavaScript validation complete\033[0m\n"

#set Findbugs Home
FINDBUGS_JAR=~/Documents/jars/findbugs-2.0.2/lib/findbugs.jar
class="class"
echo "\n\033[45mValidating Java:\033[0m\n"
CLIENT_BUILD_DIR=~/Desktop/TempDir/

if [ ! -d "$CLIENT_BUILD_DIR" ]
    then mkdir "$CLIENT_BUILD_DIR"
fi
for javafile in ${javafiles}; do
    echo "\033[31m $javafile\033[0m"
    $(javac $javafile -d $CLIENT_BUILD_DIR)
    
    javaErrors=$(java -jar "$FINDBUGS_JAR" "$CLIENT_BUILD_DIR"${javafile//java/$class})
    
    if [ ${#javaErrors} -gt 0 ]
    then
        echo "\033[31mFindbugs Failed: ${javafile}\033[0m"
        echo "$javaErrors"
        pass=false
    else
         echo "\033[32mFindbugs Passed: ${javafile}\033[0m"
    fi
    
done
rm -r "$CLIENT_BUILD_DIR"
echo "\n\033[45mJava validation complete\033[0m\n"

#grep '^Signed-off: '  >/dev/null || {
#       echo "The commit message must have a Signed-off-by line."
#       exit 1
#}

if ! $pass; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass JSLint & Findbugs but do not. Please fix the errors and try again.\n"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi


