#!/bin/sh

echo "pre-commit started"
files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then 
    exit 0 
fi

pass=true

echo "\nValidating JavaScript:\n"

for file in ${files}; do
    lintErrors=$(jslint ${file} )
    #result=$lintErrors | $( grep "${file} is OK")
    if [[ "$lintErrors" =~ .*OK.* ]]
    then
        echo "\t\033[32mJSLint Passed: ${file}\033[0m"
    else
        echo "\t\033[31mJSLint Failed: ${file}\033[0m"
        echo "$lintErrors"
        pass=false
    fi
done

echo "\nJavaScript validation complete\n"

#grep '^Signed-off: '  >/dev/null || {
#       echo "The commit message must have a Signed-off-by line."
#       exit 1
#}

if ! $pass; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass JSLint but do not. Please fix the JSLint errors and try again.\n"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi


